from . import test_album
from . import test_tag
from . import test_event
from . import test_artist
from . import test_geo
from . import test_group
from . import test_playlist
from . import test_track
from . import test_user